name: "build"

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:

jobs:
  call-build:
    uses: "KyoriPowered/.github/.github/workflows/shared-ci.yaml@trunk"
    with:
      publishing_branch_regex: 'never_publish_me' # TODO: clean up
      runtime_version: 17
    secrets: "inherit"
